spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.middleware-prod.svc.cluster.local:3306/youxiang?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: youxiang
    password: TeleInfo@12138
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
  #redis 配置
  redis:
#    database: 5  #Redis数据库索引（默认为0）
    host: redis.middleware-prod.svc.cluster.local
    port: 6379 #Redis服务器连接端口
  #  password: TeleInfo@^%>~722
    timeout: 5000MS  # 连接超时时间 单位 ms（毫秒）
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-wait: -1ms
        max-active: 200

danggui:
  filepath:
    image: "/upload/img/"
  message:
    url: "http://localhost:8080"


baidu:
  ocr:
    successUrl: "http://sdk-certification.prod.idx.space/cert/person-success?token="
    failedUrl: "http://sdk-certification.prod.idx.space/cert/person-success?token="

qrcode:
  url: "http://danggui.prod.idx.space/static/"

company:
  certify:
    url: "http://sdk-certification.prod.idx.space/cert/enterprise-cert?token="
  baiduOcr:
    callbackUrl: "http://sdk-certification.prod.idx.space/cert/authing-result?verifyToken="
  applicationCount: 10
  createCompanyCount: 6
  inviteUserCount: 50

teleInfo:
  did: did:bid:abcd:ssP7ifupbKZlXIadgy6w9oh8paykmK9g==
  bbs:
    privateKey: 3ZSoEjdijBDo5o8bnwJ5tTVryh8EEaHGr1g3nhmTpiJf
    publicKey: 23sEm7Vp8dFoLfKSopDuTkWWFPH3oWuREuaXAb1S6MbfzqvgeK4gLmUZKZ8sn9eNTNkgqxbGxjxVfkiwLtpA7HqY4NwDhSWbbUUxiJR1YgeDeKYizyPf2SnMH9r5QpVLrNP5

shortUrlPrefix: "https://s.idx.space/b/"

phone:
  encryptKey: "fc62a6433c7f3bba5c39f243e57b77afb21c2cae6fc3af10960cb875336e97f8"


project:
  domain: "http://danggui.prod.idx.space"

vp:
  domain: http://youxiang-grpc.prod.idx.space

nats:
  url: nats.middleware-prod.svc.cluster.local:4222

chain:
  address:
    did: did:bid:abcd:sfnhXnyeoLNL5aRcq2J8SQTy5wQ8W2FH
    evidence: did:bid:abcd:sf23WGD3VQ5MU6LKnZcG963FYeG5UVBcu
